RIGHT_MOTOR_PWM = 5
LEFT_MOTOR_PWM = 6
RIGHT_MOTOR_DIRECTION = 17
LEFT_MOTOR_DIRECTION = 9
ENCODER_RIGHT_A = 18
ENCODER_RIGHT_B = 19
ENCODER_LEFT_A = 3
ENCODER_LEFT_B = 7
WHEEL_RADIUS = 35 #mm
QUANTITY_OF_TICS = 340
DISTANCE_BETWEEN_WHEELS = 141 #mm
KP = 40
KI = 1
KD = 1

KP_DISTANCE = 10
KI_DISTANCE = 0
KD_DISTANCE = 2
MAXIMUM_VELOCITY = 1000

LIMIT_VELOCITY = 0.5